CREATE TABLE `ai_training` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`activePersonaTemplate` varchar(50),
	`humorLevel` int NOT NULL DEFAULT 3,
	`friendlinessLevel` int NOT NULL DEFAULT 3,
	`formalityLevel` int NOT NULL DEFAULT 3,
	`enthusiasmLevel` int NOT NULL DEFAULT 3,
	`patienceLevel` int NOT NULL DEFAULT 3,
	`empathyLevel` int NOT NULL DEFAULT 3,
	`responseLength` int NOT NULL DEFAULT 3,
	`responseDepth` int NOT NULL DEFAULT 3,
	`exampleUsage` int NOT NULL DEFAULT 3,
	`dataUsage` int NOT NULL DEFAULT 3,
	`metaphorUsage` int NOT NULL DEFAULT 3,
	`structuredResponse` int NOT NULL DEFAULT 3,
	`proactiveness` int NOT NULL DEFAULT 3,
	`questioningStyle` int NOT NULL DEFAULT 3,
	`suggestionFrequency` int NOT NULL DEFAULT 3,
	`humilityLevel` int NOT NULL DEFAULT 3,
	`persistenceLevel` int NOT NULL DEFAULT 3,
	`careLevel` int NOT NULL DEFAULT 3,
	`pushIntensity` int NOT NULL DEFAULT 3,
	`urgencyCreation` int NOT NULL DEFAULT 3,
	`priceSensitivity` int NOT NULL DEFAULT 3,
	`comparisonUsage` int NOT NULL DEFAULT 3,
	`closingIntensity` int NOT NULL DEFAULT 3,
	`followUpFrequency` int NOT NULL DEFAULT 3,
	`terminologyUsage` int NOT NULL DEFAULT 3,
	`regulationAwareness` int NOT NULL DEFAULT 3,
	`riskWarningLevel` int NOT NULL DEFAULT 3,
	`caseStudyUsage` int NOT NULL DEFAULT 3,
	`marketAnalysis` int NOT NULL DEFAULT 3,
	`educationalContent` int NOT NULL DEFAULT 3,
	`soothingAbility` int NOT NULL DEFAULT 3,
	`praiseFrequency` int NOT NULL DEFAULT 3,
	`encouragementLevel` int NOT NULL DEFAULT 3,
	`negativeHandling` int NOT NULL DEFAULT 3,
	`optimismLevel` int NOT NULL DEFAULT 3,
	`humorInTension` int NOT NULL DEFAULT 3,
	`emojiUsage` int NOT NULL DEFAULT 3,
	`colloquialLevel` int NOT NULL DEFAULT 3,
	`cantoneseUsage` int NOT NULL DEFAULT 3,
	`englishMixing` int NOT NULL DEFAULT 3,
	`exclamationUsage` int NOT NULL DEFAULT 3,
	`addressingStyle` int NOT NULL DEFAULT 3,
	`topicRange` int NOT NULL DEFAULT 3,
	`privacyAwareness` int NOT NULL DEFAULT 3,
	`promiseCaution` int NOT NULL DEFAULT 3,
	`referralWillingness` int NOT NULL DEFAULT 3,
	`uncertaintyHandling` int NOT NULL DEFAULT 3,
	`complaintHandling` int NOT NULL DEFAULT 3,
	`behaviorInstructions` text,
	`prohibitedActions` text,
	`customGreeting` text,
	`customClosing` text,
	`customPhrases` text,
	`trainingProgress` int NOT NULL DEFAULT 0,
	`intelligenceScore` int NOT NULL DEFAULT 50,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_training_id` PRIMARY KEY(`id`),
	CONSTRAINT `ai_training_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `superpowers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`instantResearch` boolean NOT NULL DEFAULT false,
	`globalComparison` boolean NOT NULL DEFAULT false,
	`legalInterpretation` boolean NOT NULL DEFAULT false,
	`caseSearch` boolean NOT NULL DEFAULT false,
	`cloneAbility` boolean NOT NULL DEFAULT true,
	`perfectMemory` boolean NOT NULL DEFAULT true,
	`alwaysOnline` boolean NOT NULL DEFAULT true,
	`instantReply` boolean NOT NULL DEFAULT true,
	`needsPrediction` boolean NOT NULL DEFAULT false,
	`riskWarning` boolean NOT NULL DEFAULT false,
	`bestTiming` boolean NOT NULL DEFAULT false,
	`marketRadar` boolean NOT NULL DEFAULT false,
	`multiLanguage` boolean NOT NULL DEFAULT true,
	`globalInfo` boolean NOT NULL DEFAULT false,
	`emotionSense` boolean NOT NULL DEFAULT false,
	`persuasionMaster` boolean NOT NULL DEFAULT false,
	`styleAdaptation` boolean NOT NULL DEFAULT false,
	`researchDepth` enum('quick','standard','deep') DEFAULT 'standard',
	`followUpIntensity` int DEFAULT 3,
	`persuasionStyle` enum('gentle','balanced','aggressive') DEFAULT 'balanced',
	`superpowerLevel` int NOT NULL DEFAULT 1,
	`totalConversationsHandled` int NOT NULL DEFAULT 0,
	`customersRemembered` int NOT NULL DEFAULT 0,
	`afterHoursMessages` int NOT NULL DEFAULT 0,
	`researchReportsGenerated` int NOT NULL DEFAULT 0,
	`predictionsAccurate` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `superpowers_id` PRIMARY KEY(`id`),
	CONSTRAINT `superpowers_userId_unique` UNIQUE(`userId`)
);
